- alias: front exterior on
  trigger:
    platform: sun
    event: sunset
  action:
    service: switch.turn_on
    entity_id: switch.front_exterior

- alias: front exterior off
  trigger:
    platform: sun
    event: sunrise
    offset: "00:20:00"
  action:
    service: switch.turn_off
    entity_id: switch.front_exterior