- alias: Living Room Off
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_motion
    to: 'off'
    for:
      minutes: 7
  action:
    service: switch.turn_off
    entity_id: switch.lr_lamp