- alias: Dining Room Lights Off
  trigger:
    platform: state
    entity_id: binary_sensor.dining_room_motion
    to: 'off'
    for:
      minutes: 7
  action:
    service: switch.turn_off
    entity_id: switch.dining_room