- alias: Dining Room Motion
  trigger:
    platform: state
    entity_id: binary_sensor.dining_room_motion
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.dining_room
  condition: 
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: '-00:40:00'
      - condition: sun  
        before: sunrise
        before_offset: '01:25:00'
      
